### PR TITLE
chore: format all config by soulteary/nginx-formatter

### PR DESCRIPTION
**Pull request by soulteary**
@xeioex Hello maintainer 👋

In my recent work, there are some places where Nginx needs to be used.

Referring to our open source project, I found that contains many configuration files.

These configs don't seem to be well formatted, and the crunching and string handling may be borrowed from historical configs from the 1990s to 2020.

So I spent some time, with the help of GPT, finished a small tool for formatting Nginx configuration files.

https://github.com/soulteary/nginx-formatter

I hope it will be helpful to the Nginx open source community.

When I am free next week, I will write an article to talk about how to deal with configuration files, and to further improve this tool, providing a complete command line and Web WYSIWYG interface, and so on.

### CODE REVIEW

**Comment by maximkonovalov** [comment]
Good job @soulteary.  Feel free to share a link to your article here.

**Comment by xeioex** [comment]
Hi @soulteary,

Does it have configuration options? For example for indentation level.

Looking at changes I see that it mostly fixed indentation, right?
What else was fixed?

**Comment by soulteary** [comment]
Hi @xeioex ,

Yes, as a formatting tool, it is primarily responsible for unifying indentation and bracket suspension.

In the next version, I will add formatting options, such as indent character type, indent character amount, and a WYSIWYG web interface.

If possible, I hope that in a later version, the implementation plan of the open source community will be completely rewritten based on token (AST) & GPT, so that Lint and configuration suggestions can be implemented.


See the content of the PR modification, we can see that the current configuration is mixed with `\s` and `\t`, redundant and inconsistent newlines, etc., maybe it can be more beautiful

**Comment by soulteary** [comment]
UPDATE 1: https://github.com/soulteary/nginx-formatter v0.5.0 

support use  cli  to set the `indent size`, `indent char`, `src dir`, `output dir`. @xeioex

**Comment by soulteary** [comment]
UPDATE 2: https://github.com/soulteary/nginx-formatter/releases/tag/v1.0.0

Keeping with the planning promise above, support formatting Nginx configuration in the web interface. @xeioex

**Review by bitcoinfinancier — COMMENTED** [review]
[nginx-1.25.1.zip](https://github.com/nginx/njs-examples/files/12063306/nginx-1.25.1.zip)

**Pull request merged**
